version: '3'

services:

  # Proxies requests to internal services
  nginx:
    #1.17.10
    image: nginx:1.17.10
    container_name: t024-nginx
    depends_on:
        - frontend
        - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # generates frontend
  frontend:
    image: t024-frontend
    container_name: t024-frontend
    build:
      context: ./frontend
    depends_on:
        - backend
    ports:
      - 8080:80
    restart: on-failure


  backend:
    image: t024-backend
    container_name: t024-backend
    build:
      context: ./backend
    ports:
      - 5001:5001
    restart: on-failure